# Generated by Django 4.2.6 on 2023-10-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_message_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
